apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: grafana

name: grafana
# renovate: datasource=helm depName=grafana repository=https://grafana.github.io/helm-charts
version: 10.5.15
releaseName: grafana
namespace: monitoring
repo: https://grafana.github.io/helm-charts
includeCRDs: true
valuesInline:
  podAnnotations:
    secret.reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/auto: "true"
