apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - dnsconfig.yaml
  - pvc.yaml
  - service.yaml

images:
  - name: ghcr.io/tailscale/tsidp
    newTag: v0.0.11
