apiVersion: v1
kind: Service

metadata:
  name: tsidp
  namespace: tailscale

spec:
  selector:
    app: tsidp
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
