[env]
KUBECONFIG = "{{config_root}}/homelab-prod.kubeconfig"
TALOSCONFIG = "{{config_root}}/homelab-prod.talosconfig"

[tools]
"aqua:argoproj/argo-cd" = "3.2.6"
"aqua:aws/aws-cli" = "2.33.13"
"aqua:hashicorp/terraform" = "1.14.4"
"aqua:helm/helm" = "3.20.0"
"aqua:go-task/task" = "3.48.0"
"aqua:gruntwork-io/terragrunt" = "0.99.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.8.0"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.0"
"aqua:siderolabs/talos" = "1.12.2"
"github:hairyhenderson/gomplate" = "4.3.3"
"github:trufflesecurity/trufflehog" = "3.92.5"
