[env]
KUBECONFIG = "{{config_root}}/homelab-prod.kubeconfig"
TALOSCONFIG = "{{config_root}}/homelab-prod.talosconfig"

[tools]
"aqua:argoproj/argo-cd" = "3.3.1"
"aqua:argoproj/argo-workflows" = "4.0.1"
"aqua:aws/aws-cli" = "2.33.26"
"aqua:go-task/task" = "3.48.0"
"aqua:gruntwork-io/terragrunt" = "0.99.4"
"aqua:hairyhenderson/gomplate" = "5.0.0"
"aqua:hashicorp/terraform" = "1.14.5"
"aqua:helm/helm" = "4.1.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.8.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "4.52.4"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:terraform-docs/terraform-docs" = "0.21.0"
"aqua:terraform-linters/tflint" = "v0.61.0"
"aqua:trufflesecurity/trufflehog" = "3.93.3"
