apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: headlamp

valuesInline:
  config:
    # TODO: tsidp doesn't seem to work natively with Headlamp. Will need to investigate whether standalone Dex will resolve this.
    oidc:
      secret:
        create: false
      externalSecret:
        enabled: true
        name: headlamp-oidc
