apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - patches

resources:
  - ../../../../bases/argocd
  - application.yaml
  - applicationset.yaml
  - argocd-rbac-cm.yaml
  - ssh-secret.yaml
  - tsidp-secret.yaml
  - tailscale-ingress.yaml
