apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: argocd-tsidp-secret
  namespace: argocd

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-tsidp-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tsidp-argocd/client_id
    - secretKey: client_secret
      remoteRef:
        key: tsidp-argocd/client_secret
