apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: headlamp

name: headlamp
# renovate: datasource=helm depName=headlamp repository=https://kubernetes-sigs.github.io/headlamp/
version: 0.40.0
releaseName: headlamp
namespace: selfhosted
repo: https://kubernetes-sigs.github.io/headlamp/
includeCRDs: true
valuesInline:
  # TODO: Add reloader annotations
