apiVersion: v1
kind: Service

metadata:
  annotations:
    tailscale.com/tailnet-fqdn: idp.neon-wyrm.ts.net
  name: tsidp-egress
  namespace: tailscale

spec:
  externalName: placeholder   # will be overwritten by operator
  type: ExternalName
