apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: environment-variables
  namespace: argo-workflows

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: terraform-aws/aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: terraform-aws/aws_secret_access_key
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: discord/webhook_url
    - secretKey: GRAFANA_AUTH
      remoteRef:
        key: terraform-grafana/credential
    - secretKey: GRAFANA_URL
      remoteRef:
        key: terraform-grafana/url
    - secretKey: OP_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: op-sa-terraform/credential
    - secretKey: ARGOCD_AUTH_TOKEN
      remoteRef:
        key: argocd/credential
    - secretKey: ARGOCD_SERVER
      remoteRef:
        key: argocd/url
    - secretKey: TG_BUCKET
      remoteRef:
        key: terraform-aws/bucket
