apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - patches

resources:
  - ../../../../../bases/argocd
  - application.yaml
  - argocd-rbac-cm.yaml
  - homelab-applicationset.yaml
  - ingress.yaml
  - ssh-secret.yaml
  - tsidp-secret.yaml
