apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: onepassword

spec:
  provider:
    onepasswordSDK:
      vault: Homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          namespace: cluster-services
          key: token
      integrationInfo:
        name: integration-info
        version: v1
