apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: reloader-alert-webhook
  namespace: cluster-services

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: reloader-alert-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: reloader-alert-webhook/url
