apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: cilium

valuesInline:
  ipv4NativeRoutingCIDR: 10.244.0.0/16

  # https://docs.siderolabs.com/kubernetes-guides/cni/deploying-cilium#method-1:-helm-install
  ipam:
    mode: kubernetes

  operator:
    replicas: 1

  # https://tailscale.com/kb/1236/kubernetes-operator#cilium-in-kube-proxy-replacement-mode
  # routingMode: native
  # socketLB:
  #   hostNamespaceOnly: true
