apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: grafana-tsidp-secret
  namespace: monitoring

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-tsidp-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tsidp-grafana/client_id
    - secretKey: client_secret
      remoteRef:
        key: tsidp-grafana/client_secret
