machine:
  sysctls:
    fs.inotify.max_user_watches: "1048576"      # Watchdog
    fs.inotify.max_user_instances: "8192"       # Watchdog
    net.ipv4.neigh.default.gc_thresh1: "4096"   # Prevent ARP cache overflows
    net.ipv4.neigh.default.gc_thresh2: "8192"   # Prevent ARP cache overflows
    net.ipv4.neigh.default.gc_thresh3: "16384"  # Prevent ARP cache overflows
    net.ipv4.tcp_slow_start_after_idle: "0"     # Preserve congestion window after idle
    user.max_user_namespaces: "11255"           # User Namespaces

  time:
    disabled: false
    servers:
      - time.cloudflare.com

  files:
    - op: create
      path: /etc/cri/conf.d/20-customization.part
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          device_ownership_from_security_context = true
