apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - discord.yaml
  - git.yaml
  - terragrunt.yaml

images:
  - name: alpine
    newTag: "3.23.3"
  - name: ghcr.io/jdx/mise
    newTag: "2026.2.15"
  - name: quay.io/argoproj/argocd
    newTag: "v3.3.1"
