apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discord.yaml
  - git.yaml
  - terragrunt.yaml

images:
  - name: alpine
    newTag: "3.23.3"
  - name: debian
    newTag: "bookworm-slim"
