apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discord.yaml
  - git-clone.yaml
  - terragrunt.yaml

images:
  - name: curlimages/curl
    newTag: "8.17.0"
  - name: alpine
    newTag: "3.23.3"
  - name: alpine/terragrunt
    newTag: "1.13.5"
