apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - patches

resources:
  - ../../../../../bases/jellyfin
  - tailscale-ingress.yaml

patches:
  - target:
      kind: ServiceAccount
      name: jellyfin
    patch: |-
      - op: add
        path: /metadata/namespace
        value: selfhosted
  - target:
      kind: Service
      name: jellyfin
    patch: |-
      - op: add
        path: /metadata/namespace
        value: selfhosted
  - target:
      kind: Deployment
      name: jellyfin
    patch: |-
      - op: add
        path: /metadata/namespace
        value: selfhosted
