apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: pve-exporter-credentials
  namespace: monitoring

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: PVE_TOKEN_NAME
      remoteRef:
        key: pve-exporter/PVE_TOKEN_NAME
    - secretKey: PVE_TOKEN_VALUE
      remoteRef:
        key: pve-exporter/PVE_TOKEN_VALUE
    - secretKey: PVE_USER
      remoteRef:
        key: pve-exporter/PVE_USER
    - secretKey: PVE_VERIFY_SSL
      remoteRef:
        key: pve-exporter/PVE_VERIFY_SSL
