apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus-pve-exporter
  namespace: monitoring

spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pve-exporter
  template:
    metadata:
      labels:
        app: prometheus-pve-exporter
      annotations:
        secret.reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter
          ports:
            - containerPort: 9221
              name: metrics
          envFrom:
            - secretRef:
                name: pve-exporter-credentials
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "256Mi"
