apiVersion: v1
kind: Service

metadata:
  name: prometheus-pve-exporter
  namespace: monitoring

spec:
  selector:
    app: prometheus-pve-exporter
  ports:
    - port: 9221
      targetPort: 9221
      name: metrics
  type: ClusterIP
