apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-services

resources:
  - github.com/alex1989hu/kubelet-serving-cert-approver/deploy/standalone?ref=v0.10.2

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kubelet-serving-cert-approver
  - target:
      kind: RoleBinding
      name: events:kubelet-serving-cert-approver
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: cluster-services
