apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Workflows
  - terragrunt.yaml
  # Workflow Templates
  - templates/discord.yaml
  - templates/git-clone.yaml
  - templates/terragrunt.yaml

images:
  - name: curlimages/curl
    newTag: "8.17.0"
  - name: alpine/terragrunt
    newTag: "1.13.5"
  - name: alpine/git
    newTag: "2.49.1"
